services:
  dbgo:
    container_name: godb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@06
      POSTGRES_DB: vendas
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}
