-- TABELA DE CLIENTES
CREATE TABLE customers(
  customer_id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(11) UNIQUE,
  cpf VARCHAR(15) NOT NULL UNIQUE,
  cnpj VARCHAR(30) UNIQUE,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_t TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- TABELA DE PRODUTOS
CREATE TABLE products(
  product_id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  price DECIMAL(10, 2) NOT NULL,
  code  INT NOT NULL UNIQUE,
  validity DATE NOT NULL,
  stock INT NOT NULL,
  entrace DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- TABETABELA IVOT
CREATE TABLE customers_products(
  id_customer_product SERIAL PRIMARY KEY,
  id_customer INT,
  id_product INT,

  FOREING KEY (id_customer) REFERENCES customers (customer_id),
  FOREING KEY (id_product) REFERENCES products (product_id)
);
