-- AQUI VAI MEUS COMANDOS SQL PARA EU CRIAR AS OUTRAS TABELAS

-- TABELA DE  PRODUTOS

CREATE TYPE status AS ENUM ('ATIVO', 'INATIVO');

CREATE TABELA produtos(
  produtos_id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code INT NOT NULL UNIQUE,
  price DECIMAL(10, 2) NOT NULL,
  stock INT NOT NULL,
  status status NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP 

  customer_id INT REFERENCES customers(customer_id)
);
